# Generated by Django 3.1.6 on 2021-02-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_day', models.IntegerField(verbose_name='Число')),
                ('week_day', models.CharField(max_length=9, verbose_name='День недели')),
                ('image_small',
                 models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение предпросмотра')),
                (
                'image_big', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение статьи')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема')),
                ('title', models.CharField(max_length=100, verbose_name='Названия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('short_desc', models.TextField(max_length=300, verbose_name='Короткое описание')),
                ('full_desc', models.TextField(verbose_name='Текст статьи')),
                ('text_button', models.CharField(max_length=15, verbose_name='Текст кнопки ')),
            ],
        ),
    ]
