# Generated by Django 3.1.6 on 2021-02-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text_button',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='theme',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титул'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='week_day',
            field=models.CharField(max_length=20, verbose_name='День недели'),
        ),
    ]
