# Generated by Django 3.1.6 on 2021-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20210215_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение предпросмотра'),
        ),
    ]
