# Generated by Django 3.1.6 on 2021-02-15 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20210215_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_ru',
            new_name='category_pl',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='full_desc_ru',
            new_name='full_desc_pl',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='short_desc_ru',
            new_name='short_desc_pl',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title_ru',
            new_name='title_pl',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='week_day_ru',
            new_name='week_day_pl',
        ),
    ]
