# Generated by Django 3.1.6 on 2021-02-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20210215_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='week_day',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='week_day_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='week_day_pl',
        ),
        migrations.AddField(
            model_name='blog',
            name='months',
            field=models.CharField(default=43, max_length=5, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='months_en',
            field=models.CharField(max_length=5, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='blog',
            name='months_pl',
            field=models.CharField(max_length=5, null=True, verbose_name='Месяц'),
        ),
    ]
