# Generated by Django 3.1.6 on 2021-02-17 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20210215_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_pl',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='full_desc_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='full_desc_pl',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='full_desc_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='months_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='months_pl',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='months_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_desc_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_desc_pl',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_desc_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_ru',
        ),
    ]
