# Generated by Django 3.0.8 on 2021-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20210215_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='blog_detail', verbose_name='Изображение статьи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='blog_article',
                                    verbose_name='Изображение предпросмотра'),
        ),
    ]
