# Generated by Django 3.1.6 on 2021-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20210217_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение предпросмотра'),
        ),
    ]
