# Generated by Django 3.1.6 on 2021-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_auto_20210218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_detail',
                                    verbose_name='Изображение статьи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_article',
                                    verbose_name='Изображение предпросмотра'),
        ),
    ]
