# Generated by Django 3.0.8 on 2021-02-18 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0015_auto_20210218_1151'),
        ('blog', '0009_auto_20210218_1627'),
    ]

    operations = [
    ]
