# Generated by Django 3.0.8 on 2021-02-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0018_auto_20210219_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Wpisy'},
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
