# Generated by Django 3.0.8 on 2021-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0019_auto_20210219_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_small',
                 models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Изображение предпросмотра')),
                ('image_big',
                 models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Изображение статьи')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('title_pl', models.CharField(max_length=100, null=True, verbose_name='Титул')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Титул')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Титул')),
                ('date', models.DateField(verbose_name='Дата')),
                ('short_desc', models.TextField(max_length=300, verbose_name='Короткое описание')),
                ('short_desc_pl', models.TextField(max_length=300, null=True, verbose_name='Короткое описание')),
                ('short_desc_ru', models.TextField(max_length=300, null=True, verbose_name='Короткое описание')),
                ('short_desc_en', models.TextField(max_length=300, null=True, verbose_name='Короткое описание')),
                ('full_desc', models.TextField(verbose_name='Текст статьи')),
                ('full_desc_pl', models.TextField(null=True, verbose_name='Текст статьи')),
                ('full_desc_ru', models.TextField(null=True, verbose_name='Текст статьи')),
                ('full_desc_en', models.TextField(null=True, verbose_name='Текст статьи')),
                ('slug', models.SlugField(default='slug')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Wpisy',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
