# Generated by Django 3.1.5 on 2021-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210219_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Wpis', 'verbose_name_plural': 'Wpisy'},
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_desc',
            field=models.TextField(verbose_name='Zawartosć artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_desc_en',
            field=models.TextField(null=True, verbose_name='Zawartosć artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_desc_pl',
            field=models.TextField(null=True, verbose_name='Zawartosć artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_desc_ru',
            field=models.TextField(null=True, verbose_name='Zawartosć artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_big',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Obraz artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Obraz podglądu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc',
            field=models.TextField(max_length=300, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_pl',
            field=models.TextField(max_length=300, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa artykułu'),
        ),
    ]
