# Generated by Django 3.1.7 on 2021-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210225_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_desc_uk',
            field=models.TextField(null=True, verbose_name='Zawartosć artykułu'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_desc_uk',
            field=models.TextField(max_length=300, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Nazwa artykułu'),
        ),
    ]
