# Generated by Django 3.0.8 on 2021-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210426_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_desc',
            field=models.TextField(max_length=1200, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_en',
            field=models.TextField(max_length=1200, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_pl',
            field=models.TextField(max_length=1200, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_ru',
            field=models.TextField(max_length=1200, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_desc_uk',
            field=models.TextField(max_length=1200, null=True, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa artykułu'),
        ),
    ]
