# Generated by Django 3.1.7 on 2021-03-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210319_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Kategoria',
            new_name='category',
        ),
    ]
