# Generated by Django 3.1.7 on 2021-03-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210321_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesories',
            options={'verbose_name': 'Akcesoria', 'verbose_name_plural': 'Akcesoria'},
        ),
    ]
