# Generated by Django 3.1.7 on 2021-03-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210321_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesories',
            name='imag',
        ),
    ]
