# Generated by Django 3.1.7 on 2021-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_accesories_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nazwa stanowiska')),
                ('desc', models.TextField(max_length=4000, verbose_name='Tekst ogłoszenia')),
            ],
            options={
                'verbose_name': 'Praca',
                'verbose_name_plural': 'Praca',
            },
        ),
    ]
