# Generated by Django 3.1.7 on 2021-03-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.TextField(max_length=20000, verbose_name='Tekst ogłoszenia'),
        ),
    ]
