# Generated by Django 3.1.7 on 2021-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210322_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, help_text='Zdjęcie bloku tekstowego', null=True, upload_to='work_img', verbose_name='Zdjęcie bloku tekstowego'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='image',
            field=models.ImageField(blank=True, help_text='Zdjęcie kursu', null=True, upload_to='learning_img', verbose_name='Zdjęcie kursu'),
        ),
    ]
