# Generated by Django 3.1.7 on 2021-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_service_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='promo_en',
            field=models.TextField(blank=True, help_text='Tekst pod tytułem usługi na stronie usługi', null=True, verbose_name='Promocja'),
        ),
        migrations.AddField(
            model_name='service',
            name='promo_pl',
            field=models.TextField(blank=True, help_text='Tekst pod tytułem usługi na stronie usługi', null=True, verbose_name='Promocja'),
        ),
        migrations.AddField(
            model_name='service',
            name='promo_ru',
            field=models.TextField(blank=True, help_text='Tekst pod tytułem usługi na stronie usługi', null=True, verbose_name='Promocja'),
        ),
    ]
