# Generated by Django 3.1.7 on 2021-03-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210326_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stolbiec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolbik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Столбец колонки(название)')),
                ('stolbiec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stolbiec', to='main.service')),
            ],
            options={
                'verbose_name': 'Столбик',
                'verbose_name_plural': 'Столбцы',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ряд таблицы(Цена)')),
                ('rows', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='main.stolbiec')),
            ],
            options={
                'verbose_name': 'Ряд',
                'verbose_name_plural': 'Ряды',
            },
        ),
    ]
