# Generated by Django 3.1.7 on 2021-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210327_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='choise',
            field=models.CharField(choices=[('Przycisk', 'Przycisk')], default='', max_length=100),
        ),
    ]
