# Generated by Django 3.1.7 on 2021-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210327_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'verbose_name': 'Wiersz', 'verbose_name_plural': 'Wiersze'},
        ),
        migrations.AlterModelOptions(
            name='stolbiec',
            options={'ordering': ['my_order'], 'verbose_name': 'Kolumna', 'verbose_name_plural': 'Kolumny'},
        ),
        migrations.AlterField(
            model_name='row',
            name='row',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł wiersza'),
        ),
        migrations.AlterField(
            model_name='stolbiec',
            name='stolbik',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł kolumny'),
        ),
    ]
