# Generated by Django 3.1.7 on 2021-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210406_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesories',
            name='name_uk',
            field=models.TextField(max_length=1000, null=True, verbose_name='Nazwa towaru'),
        ),
        migrations.AddField(
            model_name='accesories',
            name='price_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Cena towaru'),
        ),
        migrations.AddField(
            model_name='learning',
            name='desc_uk',
            field=models.TextField(max_length=20000, null=True, verbose_name='Tekst kursu'),
        ),
        migrations.AddField(
            model_name='learning',
            name='name_uk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nazwa kursu'),
        ),
        migrations.AddField(
            model_name='review',
            name='desc_uk',
            field=models.TextField(null=True, verbose_name='Tekst opinii'),
        ),
        migrations.AddField(
            model_name='review',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Imie'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uk',
            field=models.CharField(help_text='Nazwa usługi w menu', max_length=200, null=True, verbose_name='Nazwa usługi'),
        ),
        migrations.AddField(
            model_name='service',
            name='promo_uk',
            field=models.TextField(blank=True, help_text='Tekst pod tytułem usługi na stronie usługi', null=True, verbose_name='Promocja'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_uk',
            field=models.TextField(blank=True, help_text='Tekst bloku tekstowego', null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uk',
            field=models.CharField(blank=True, help_text='Tytuł bloku tekstowego', max_length=200, null=True, verbose_name='Nazwa usługi'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_desc_uk',
            field=models.TextField(max_length=400, null=True, verbose_name='Opis pracownika'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_surname_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Imie i Nazwisko pracownika'),
        ),
        migrations.AddField(
            model_name='team',
            name='post_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Stanowisko pracownika'),
        ),
        migrations.AddField(
            model_name='work',
            name='desc_uk',
            field=models.TextField(max_length=20000, null=True, verbose_name='Tekst ogłoszenia'),
        ),
        migrations.AddField(
            model_name='work',
            name='name_uk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nazwa stanowiska'),
        ),
    ]
