# Generated by Django 3.0.8 on 2021-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210426_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolbiec',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
    ]
