# Generated by Django 3.0.8 on 2021-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_service_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='test_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='service',
            name='test_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='service',
            name='test_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='service',
            name='test_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
    ]
