# Generated by Django 3.0.8 on 2021-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210626_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='stolbiec',
            name='stolbik_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł kolumny'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='stolbik_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł kolumny'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='stolbik_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł kolumny'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='stolbik_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł kolumny'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='test_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='test_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='test_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
        migrations.AddField(
            model_name='stolbiec',
            name='test_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TEST'),
        ),
    ]
