# Generated by Django 3.0.8 on 2021-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210626_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='test',
        ),
        migrations.RemoveField(
            model_name='service',
            name='test_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='test_pl',
        ),
        migrations.RemoveField(
            model_name='service',
            name='test_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='test_uk',
        ),
        migrations.RemoveField(
            model_name='stolbiec',
            name='test',
        ),
        migrations.RemoveField(
            model_name='stolbiec',
            name='test_en',
        ),
        migrations.RemoveField(
            model_name='stolbiec',
            name='test_pl',
        ),
        migrations.RemoveField(
            model_name='stolbiec',
            name='test_ru',
        ),
        migrations.RemoveField(
            model_name='stolbiec',
            name='test_uk',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Nazwa urządzenia w menu', max_length=200, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(help_text='Nazwa urządzenia w menu', max_length=200, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Nazwa urządzenia w menu', max_length=200, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(help_text='Nazwa urządzenia w menu', max_length=200, null=True, verbose_name='Kategoria'),
        ),
    ]
